# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bd34756f5ce5493d24487e337646161d67125fdce25c32da148e1c668a52decabb8bcac82cd886a886f886576cb13bd1098f66f88c3eada7523c96b53635f94

test:
  secret_key_base: 07ec0a5cb8d17d2a635e7a2dfdfac9da699d16fc91d0d82b419d39c9008a1d2d57c17552ce29755f81cf4af320113810483701c256eda16a397f84cb2667fcb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
